Upgrade wkt package version to fix a bug involving multipoint.
Without the package upgrade we panic with this error:

`thread 'to_geo::test::geom_to_geo_multipoint' panicked at 'called `Result::unwrap()` on an `Err` value: ConversionError("impossible to read wkt: Missing closing parenthesis for type")', src/to_geo.rs:82:59`